---
apiVersion: apps/v1
kind: Service
metadata:
  name: po-lin-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensy-mongo
  template:
    metadata:
      labels:
        app: expensy-mongo
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort: 27017
       
