---
apiVersion: v1
kind: Service
metadata:
  name: mongo   
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
 

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
#   annotations:
#     prometheus.io/scrape: 'true'
#     prometheus.io/port: 'YOUR_METRICS_PORT'
# spec:
#   selector:
#     matchLabels:
#       app: expensy-mongo
#     spec:
#       containers:
#       - name: mongo-container
#         image: mongo
#         ports:
#         - containerPort: 27017
